service: everybaby
app: everybaby
org: denialanderror
frameworkVersion: "=1.51.0"

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: arn:aws:sns:*:*:*
    - Effect: Allow
      Action:
        - logs:CreateLogGroup,
        - logs:CreateLogStream,
        - logs:PutLogEvents,
        - logs:DescribeLogStreams
      Resource: "arn:aws:logs:*:*:*"

functions:
  findAndNotify:
    handler: handler.findAndNotify
    events:
      - schedule: cron(0 9 ? * WED *)
    environment:
      topicArn: arn:aws:sns:eu-west-2:917755463306:everymanbaby-topic
      email: denialanderror@googlemail.com
